### ISSUE TITLE
Flaky `test_run_conv_model`

### ISSUE THREAD

**Issue by Syzygianinfern0** [OpenMined/SyMPC#212]
## Description
The `test_run_conv_model` test is flaky

https://github.com/OpenMined/SyMPC/blob/95e351db48172fd2df0d89383a3023cb747306da/tests/sympc/module/module_test.py#L91

## How to Reproduce
Run the test a bunch of times :stuck_out_tongue:.

## Expected Behavior
The test must pass reliably.
 
## Additional Context
- Fixing the `atol` parameter is usually sufficient if the values are really close.
- Sometimes, the methods used in the underlying calculations have parameters that trade-off between speed and accuracy of the approximation. Those can be tweaked to give reliable results.

> Note: @SyMPC, a reliable test must pass 30 times in a row.

**Comment by gmuraru** [comment]
Made a [PR](https://github.com/OpenMined/SyMPC/pull/234) to unblock development since this test (and some other ones) are creating more failures than normally.
I created a new [issue](https://github.com/OpenMined/SyMPC/issues/235) for increasing the tolerance and check which underlying approximations gives bad results
