### ISSUE TITLE
Fix darglist warnings

### ISSUE THREAD

**Issue by aanurraj** [OpenMined/SyMPC#73]
## Where?
The SyMPC code have some darglint warnings/errors which needs to be fixed.

## What?
when you run `$ darglint src tests ` you will find following warnings/errors.

![Screenshot 2021-03-06 at 9 58 35 PM](https://user-images.githubusercontent.com/28955148/110213702-1d4b5500-7ec7-11eb-9dda-4a5d1e054468.png)

fix this errors you can learn more about darglint warning/error codes [here](https://github.com/terrencepreilly/darglint#error-codes)

**Comment by jmaunon** [comment]
Hi @aanurraj . I was actually doing this in this issue: #60. I know that the issue was just to integrat `darglint` but at the same time I was fixing this because in some modules the documentation was not following `Google` style and some of them was just missing.

The point is that in the meantime the `docs_team` was created, and one of the goals is exactly this. This repository is quite new, so this is a great oportunity to get a better `docstring coverage`.

If you want, assign to me, and i will try to recover this task asap.

**Comment by aanurraj** [comment]
> Hi @aanurraj . I was actually doing this in this issue: #60. I know that the issue was just to integrat `darglint` but at the same time I was fixing this because in some modules the documentation was not following `Google` style and some of them was just missing.
> 
> The point is that in the meantime the `docs_team` was created, and I did not have time to finish, but one of the goals is exactly this, improve inline documentaiton of `openmined`. This repository is quite new, so this is a great oportunity to get a better `docstring coverage`, and I am more or less familiar with the codebase.
> 
> If you want, assign to me, and i will try to recover this task asap.

hi @Jasopaum sure 🥳
